### PR TITLE
Update OOM API.

### PR DESCRIPTION
**Pull request by k-sareen**
Note that JikesRVM will abort the VM immediately when an OOM is
reported. Hence, we do not have to account for the case where MMTk core
has returned a `null` pointer back to the VM due to OOM.

JikesRVM also makes no distinction between an OOM due to the OS being
unable to acquire more memory and a simple Java Heap OOM.

Associated mmtk-core PR: https://github.com/mmtk/mmtk-core/pull/535

### CODE REVIEW

**Comment by k-sareen** [comment]
Not sure what the issue is? Is it because the PR is from my fork?

**Comment by qinsoon** [comment]
> Not sure what the issue is? Is it because the PR is from my fork?

Yeah. I think so.

**Comment by k-sareen** [comment]
It's a pretty trivial PR, but it would be good to be able to test it.

**Review by qinsoon — APPROVED** [review]
LGTM

**Pull request merged**
