### PR TITLE
Bump toolchain version and MSRV

### PR DESCRIPTION
**Pull request by wks**

### CODE REVIEW

**Comment by qinsoon** [comment]
@wks I had some attempts on the issues. I can't reproduce it on moma machines. So I just debug it with our CI. I haven't fixed it yet. Here are what I found.

I logged the error. It should be this (https://github.com/mmtk/mmtk-jikesrvm/actions/runs/4214308783/jobs/7314873252):
```console
error[E0463]: can't find crate for `core`
  |
  = note: the `i686-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add i686-unknown-linux-gnu`
```

So I tried to use `--target` for `cargo msrv`. This is the new error message (https://github.com/mmtk/mmtk-jikesrvm/actions/runs/4218986281/jobs/7323931285).
```console
= note: /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libz.so when searching for -lz
          /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libz.a when searching for -lz
          /usr/bin/ld: cannot find -lz: No such file or directory
          /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libz.so when searching for -lz
          collect2: error: ld returned 1 exit status

error: could not compile `mmtk` due to previous error
```

It seems related with this issue with `cargo-msrv`: https://github.com/foresterre/cargo-msrv/issues/587. It was reported with exactly the same version of `cargo msrv` and `rust 1.66.1`.

**Comment by wks** [comment]
I guess the i686 target depends on a 32-bit version of libz, which needs to be installed via apt-get.

**Comment by qinsoon** [comment]
> I guess the i686 target depends on a 32-bit version of libz, which needs to be installed via apt-get.

Yeah. That fixed the problem. Basically, we need to supply `--target i686-unknown-linux-gnu` when running `cargo msrv` (I don't know why it worked without this before), and also we need to install the dependency.

**Review by qinsoon — APPROVED** [review]

**Comment by qinsoon** [comment]
We should merge this after https://github.com/mmtk/mmtk-core/pull/756, and change the mmtk dependency to the new commit of https://github.com/mmtk/mmtk-core/pull/756.

**Pull request merged**
